<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\Icons\Alert-Triangle\alert-triangle_control_alert_color_primary100.png" />
    <None Remove="Resources\Images\Icons\Book\book_text_color_primary80.png" />
    <None Remove="Resources\Images\Icons\Briefcase\briefcase_disabled.png" />
    <None Remove="Resources\Images\Icons\Briefcase\briefcase_text_color_primary80.png" />
    <None Remove="Resources\Images\Icons\Briefcase\briefcase_text_color_secondary120.png" />
    <None Remove="Resources\Images\Icons\Briefcase\briefcase_white.png" />
    <None Remove="Resources\Images\Icons\Calendar\calendar_accent_green.png" />
    <None Remove="Resources\Images\Icons\Edit\edit_text_color_primary80.png" />
    <None Remove="Resources\Images\Icons\Edit\edit_white.png" />
    <None Remove="Resources\Images\Icons\More-Horizontal\more-horizontal_text_control_color_primary90.png" />
    <None Remove="Resources\Images\Icons\More-Horizontal\more-horizontal_white.png" />
    <None Remove="Resources\Images\Icons\Save\save_accent_green.png" />
    <None Remove="Resources\Images\Icons\Save\save_disabled%281%29.png" />
    <None Remove="Resources\Images\Icons\Save\save_disabled.png" />
    <None Remove="Resources\Images\Icons\Save\save_text_color_primary90.png" />
    <None Remove="Resources\Images\Icons\Settings\settings_text_color_primary90.png" />
    <None Remove="Resources\Images\Icons\Trash\trash_text_color_primary80.png" />
    <None Remove="Resources\Images\Icons\X\x_text_control_color_primary90.png" />
    <None Remove="Resources\Images\Icons\X\x_white.png" />
    <None Remove="Resources\Images\Logos\fast-time.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LadleUI\LadleUI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\Icons\Alert-Triangle\alert-triangle_control_alert_color_primary100.png" />
    <Resource Include="Resources\Images\Icons\Book\book_text_color_primary80.png" />
    <Resource Include="Resources\Images\Icons\Briefcase\briefcase_disabled.png" />
    <Resource Include="Resources\Images\Icons\Briefcase\briefcase_text_color_primary80.png" />
    <Resource Include="Resources\Images\Icons\Briefcase\briefcase_text_color_secondary120.png" />
    <Resource Include="Resources\Images\Icons\Briefcase\briefcase_white.png" />
    <Resource Include="Resources\Images\Icons\Calendar\calendar_accent_green.png" />
    <Resource Include="Resources\Images\Icons\Edit\edit_text_color_primary80.png" />
    <Resource Include="Resources\Images\Icons\Edit\edit_white.png" />
    <Resource Include="Resources\Images\Icons\More-Horizontal\more-horizontal_text_control_color_primary90.png" />
    <Resource Include="Resources\Images\Icons\More-Horizontal\more-horizontal_white.png" />
    <Resource Include="Resources\Images\Icons\Save\save_accent_green.png" />
    <Resource Include="Resources\Images\Icons\Save\save_disabled.png" />
    <Resource Include="Resources\Images\Icons\Save\save_text_color_primary90.png" />
    <Resource Include="Resources\Images\Icons\Settings\settings_text_color_primary90.png" />
    <Resource Include="Resources\Images\Icons\Trash\trash_text_color_primary80.png" />
    <Resource Include="Resources\Images\Icons\X\x_text_control_color_primary90.png" />
    <Resource Include="Resources\Images\Icons\X\x_white.png" />
    <Resource Include="Resources\Images\Logos\fast-time.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
